import './globals.css'
import { Inter } from 'next/font/google'
import Header from '../components/header/Header';
import Sidebar from '../components/sidebar/Sidebar';
import Feed from '../components/feed/Feed';
const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'sahibinden.com',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header/>
        {children}
        <Feed />
        <Sidebar />
        </body>
    </html>
  )
}
